# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Project8-20240907T221810Z-001/Project main"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Project8-20240907T221810Z-001/Project main"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Project8-20240907T221810Z-001/Project main/CMakeFiles" "/Project8-20240907T221810Z-001/Project main//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Project8-20240907T221810Z-001/Project main/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HTTP_Server

# Build rule for target.
HTTP_Server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HTTP_Server
.PHONY : HTTP_Server

# fast build rule for target.
HTTP_Server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/build
.PHONY : HTTP_Server/fast

Configuration/config_parser.o: Configuration/config_parser.cpp.o
.PHONY : Configuration/config_parser.o

# target to build an object file
Configuration/config_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Configuration/config_parser.cpp.o
.PHONY : Configuration/config_parser.cpp.o

Configuration/config_parser.i: Configuration/config_parser.cpp.i
.PHONY : Configuration/config_parser.i

# target to preprocess a source file
Configuration/config_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Configuration/config_parser.cpp.i
.PHONY : Configuration/config_parser.cpp.i

Configuration/config_parser.s: Configuration/config_parser.cpp.s
.PHONY : Configuration/config_parser.s

# target to generate assembly for a file
Configuration/config_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Configuration/config_parser.cpp.s
.PHONY : Configuration/config_parser.cpp.s

Core/connection.o: Core/connection.cpp.o
.PHONY : Core/connection.o

# target to build an object file
Core/connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/connection.cpp.o
.PHONY : Core/connection.cpp.o

Core/connection.i: Core/connection.cpp.i
.PHONY : Core/connection.i

# target to preprocess a source file
Core/connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/connection.cpp.i
.PHONY : Core/connection.cpp.i

Core/connection.s: Core/connection.cpp.s
.PHONY : Core/connection.s

# target to generate assembly for a file
Core/connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/connection.cpp.s
.PHONY : Core/connection.cpp.s

Core/global.o: Core/global.cpp.o
.PHONY : Core/global.o

# target to build an object file
Core/global.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/global.cpp.o
.PHONY : Core/global.cpp.o

Core/global.i: Core/global.cpp.i
.PHONY : Core/global.i

# target to preprocess a source file
Core/global.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/global.cpp.i
.PHONY : Core/global.cpp.i

Core/global.s: Core/global.cpp.s
.PHONY : Core/global.s

# target to generate assembly for a file
Core/global.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/global.cpp.s
.PHONY : Core/global.cpp.s

Core/request_handler.o: Core/request_handler.cpp.o
.PHONY : Core/request_handler.o

# target to build an object file
Core/request_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/request_handler.cpp.o
.PHONY : Core/request_handler.cpp.o

Core/request_handler.i: Core/request_handler.cpp.i
.PHONY : Core/request_handler.i

# target to preprocess a source file
Core/request_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/request_handler.cpp.i
.PHONY : Core/request_handler.cpp.i

Core/request_handler.s: Core/request_handler.cpp.s
.PHONY : Core/request_handler.s

# target to generate assembly for a file
Core/request_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/request_handler.cpp.s
.PHONY : Core/request_handler.cpp.s

Core/response_generator.o: Core/response_generator.cpp.o
.PHONY : Core/response_generator.o

# target to build an object file
Core/response_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/response_generator.cpp.o
.PHONY : Core/response_generator.cpp.o

Core/response_generator.i: Core/response_generator.cpp.i
.PHONY : Core/response_generator.i

# target to preprocess a source file
Core/response_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/response_generator.cpp.i
.PHONY : Core/response_generator.cpp.i

Core/response_generator.s: Core/response_generator.cpp.s
.PHONY : Core/response_generator.s

# target to generate assembly for a file
Core/response_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/response_generator.cpp.s
.PHONY : Core/response_generator.cpp.s

Core/session.o: Core/session.cpp.o
.PHONY : Core/session.o

# target to build an object file
Core/session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/session.cpp.o
.PHONY : Core/session.cpp.o

Core/session.i: Core/session.cpp.i
.PHONY : Core/session.i

# target to preprocess a source file
Core/session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/session.cpp.i
.PHONY : Core/session.cpp.i

Core/session.s: Core/session.cpp.s
.PHONY : Core/session.s

# target to generate assembly for a file
Core/session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Core/session.cpp.s
.PHONY : Core/session.cpp.s

Error_handling/error_handling.o: Error_handling/error_handling.cpp.o
.PHONY : Error_handling/error_handling.o

# target to build an object file
Error_handling/error_handling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Error_handling/error_handling.cpp.o
.PHONY : Error_handling/error_handling.cpp.o

Error_handling/error_handling.i: Error_handling/error_handling.cpp.i
.PHONY : Error_handling/error_handling.i

# target to preprocess a source file
Error_handling/error_handling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Error_handling/error_handling.cpp.i
.PHONY : Error_handling/error_handling.cpp.i

Error_handling/error_handling.s: Error_handling/error_handling.cpp.s
.PHONY : Error_handling/error_handling.s

# target to generate assembly for a file
Error_handling/error_handling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Error_handling/error_handling.cpp.s
.PHONY : Error_handling/error_handling.cpp.s

File_Management/file_handler.o: File_Management/file_handler.cpp.o
.PHONY : File_Management/file_handler.o

# target to build an object file
File_Management/file_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/File_Management/file_handler.cpp.o
.PHONY : File_Management/file_handler.cpp.o

File_Management/file_handler.i: File_Management/file_handler.cpp.i
.PHONY : File_Management/file_handler.i

# target to preprocess a source file
File_Management/file_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/File_Management/file_handler.cpp.i
.PHONY : File_Management/file_handler.cpp.i

File_Management/file_handler.s: File_Management/file_handler.cpp.s
.PHONY : File_Management/file_handler.s

# target to generate assembly for a file
File_Management/file_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/File_Management/file_handler.cpp.s
.PHONY : File_Management/file_handler.cpp.s

Monitoring/monitoring.o: Monitoring/monitoring.cpp.o
.PHONY : Monitoring/monitoring.o

# target to build an object file
Monitoring/monitoring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Monitoring/monitoring.cpp.o
.PHONY : Monitoring/monitoring.cpp.o

Monitoring/monitoring.i: Monitoring/monitoring.cpp.i
.PHONY : Monitoring/monitoring.i

# target to preprocess a source file
Monitoring/monitoring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Monitoring/monitoring.cpp.i
.PHONY : Monitoring/monitoring.cpp.i

Monitoring/monitoring.s: Monitoring/monitoring.cpp.s
.PHONY : Monitoring/monitoring.s

# target to generate assembly for a file
Monitoring/monitoring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Monitoring/monitoring.cpp.s
.PHONY : Monitoring/monitoring.cpp.s

Routing/routing.o: Routing/routing.cpp.o
.PHONY : Routing/routing.o

# target to build an object file
Routing/routing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Routing/routing.cpp.o
.PHONY : Routing/routing.cpp.o

Routing/routing.i: Routing/routing.cpp.i
.PHONY : Routing/routing.i

# target to preprocess a source file
Routing/routing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Routing/routing.cpp.i
.PHONY : Routing/routing.cpp.i

Routing/routing.s: Routing/routing.cpp.s
.PHONY : Routing/routing.s

# target to generate assembly for a file
Routing/routing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Routing/routing.cpp.s
.PHONY : Routing/routing.cpp.s

Thread/thread.o: Thread/thread.cpp.o
.PHONY : Thread/thread.o

# target to build an object file
Thread/thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Thread/thread.cpp.o
.PHONY : Thread/thread.cpp.o

Thread/thread.i: Thread/thread.cpp.i
.PHONY : Thread/thread.i

# target to preprocess a source file
Thread/thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Thread/thread.cpp.i
.PHONY : Thread/thread.cpp.i

Thread/thread.s: Thread/thread.cpp.s
.PHONY : Thread/thread.s

# target to generate assembly for a file
Thread/thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/Thread/thread.cpp.s
.PHONY : Thread/thread.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HTTP_Server.dir/build.make CMakeFiles/HTTP_Server.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HTTP_Server"
	@echo "... Configuration/config_parser.o"
	@echo "... Configuration/config_parser.i"
	@echo "... Configuration/config_parser.s"
	@echo "... Core/connection.o"
	@echo "... Core/connection.i"
	@echo "... Core/connection.s"
	@echo "... Core/global.o"
	@echo "... Core/global.i"
	@echo "... Core/global.s"
	@echo "... Core/request_handler.o"
	@echo "... Core/request_handler.i"
	@echo "... Core/request_handler.s"
	@echo "... Core/response_generator.o"
	@echo "... Core/response_generator.i"
	@echo "... Core/response_generator.s"
	@echo "... Core/session.o"
	@echo "... Core/session.i"
	@echo "... Core/session.s"
	@echo "... Error_handling/error_handling.o"
	@echo "... Error_handling/error_handling.i"
	@echo "... Error_handling/error_handling.s"
	@echo "... File_Management/file_handler.o"
	@echo "... File_Management/file_handler.i"
	@echo "... File_Management/file_handler.s"
	@echo "... Monitoring/monitoring.o"
	@echo "... Monitoring/monitoring.i"
	@echo "... Monitoring/monitoring.s"
	@echo "... Routing/routing.o"
	@echo "... Routing/routing.i"
	@echo "... Routing/routing.s"
	@echo "... Thread/thread.o"
	@echo "... Thread/thread.i"
	@echo "... Thread/thread.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

